import type { Metadata } from "next";
import { kanit, barlow } from "./fonts";
import "./globals.css";
// import "./../libraries/font-awesome/font-awesome-pro-main/fontawesome-pro-6.5.1-web/css/solid.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} font-[300]`}>
        {children}
      </body>
    </html>
  );
}
